"""Answer groundedness verification evaluator using structured LLM output."""

from collections.abc import Sequence
import json
import logging
from typing import Any
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI
from pydantic import BaseModel, Field

from app.config import get_settings

logger = logging.getLogger(__name__)

GROUNDEDNESS_SYSTEM_PROMPT: str = """You are an impartial, strict factual consistency and groundedness evaluator.
Your sole job is to verify whether the factual claims in the DRAFT ANSWER are directly and explicitly supported by the provided RETRIEVED CONTEXT.

CRITICAL EVALUATION RULES:
1. Compare ONLY the DRAFT ANSWER against the RETRIEVED CONTEXT.
2. DO NOT use external or general knowledge. Even if a claim is factually true in the real world, if it is NOT directly stated in the RETRIEVED CONTEXT, it is UNGROUNDED.
3. Identify every distinct factual claim made in the DRAFT ANSWER.
4. For each claim, check whether the RETRIEVED CONTEXT contains direct supporting evidence.
5. If any factual claim is not supported, or if the context is insufficient, list the unsupported claim in 'unsupported_claims' and set 'grounded' to false.
6. Set 'grounded' to true ONLY if 100% of the factual claims in the answer are supported by the context.
7. Assign a 'grounding_score' between 0.0 (completely unsupported) and 1.0 (fully supported). If all claims are supported, grounding_score should be 1.0 (or near 1.0).
8. If the draft answer explicitly states that the document does not contain enough information to answer the question, and the context lacks information to answer, mark grounded=true, grounding_score=1.0, unsupported_claims=[].
"""


class GroundednessError(Exception):
    """Base exception for all groundedness verification failures."""


class MissingAPIKeyError(GroundednessError):
    """Raised when the OpenAI API key is missing or blank."""


class GroundednessAPIError(GroundednessError):
    """Raised when the LLM evaluation API call fails."""


class GroundednessResult(BaseModel):
    """Structured output result for groundedness evaluation."""

    grounded: bool = Field(
        ...,
        description="Whether the draft answer is fully supported by the retrieved context",
    )
    grounding_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Confidence score between 0.0 and 1.0 of factual grounding",
    )
    unsupported_claims: list[str] = Field(
        default_factory=list,
        description="List of factual claims in the draft answer not supported by the context",
    )

    def to_dict(self) -> dict[str, Any]:
        """Convert the result into a clean dictionary."""
        return self.model_dump()


def format_evaluator_prompt(
    query: str,
    draft_answer: str,
    retrieved_context: Sequence[str],
) -> str:
    """Format input into evaluator user prompt.

    Args:
        query: User question.
        draft_answer: Answer generated by the LLM.
        retrieved_context: Sequence of retrieved context strings.

    Returns:
        str: Formatted user message string.
    """
    context_blocks: list[str] = []
    for idx, c in enumerate(retrieved_context):
        clean_text = c.strip() if isinstance(c, str) else str(c).strip()
        if clean_text:
            context_blocks.append(f"[Context Chunk {idx+1}]\n{clean_text}")

    context_text = "\n\n".join(context_blocks)

    return f"""USER QUERY:
{query}

DRAFT ANSWER TO EVALUATE:
{draft_answer}

RETRIEVED CONTEXT:
{context_text}"""


class GroundednessEvaluator:
    """Evaluates whether draft answers are strictly supported by retrieved context."""

    def __init__(
        self,
        model: str | None = None,
        api_key: str | None = None,
        chat_client: Any | None = None,
    ) -> None:
        """Initialize GroundednessEvaluator with OpenAI chat client.

        Args:
            model: OpenAI chat model identifier. Defaults to settings.OPENAI_CHAT_MODEL.
            api_key: Optional OpenAI API key override.
            chat_client: Optional custom chat client or mock for testing.

        Raises:
            MissingAPIKeyError: If API key is missing when creating default client.
        """
        settings = get_settings()
        self.model = model or settings.OPENAI_CHAT_MODEL

        if chat_client is not None:
            self.client = chat_client
            if hasattr(chat_client, "model_name"):
                self.model = chat_client.model_name
        else:
            resolved_api_key = (
                api_key if api_key is not None else settings.OPENAI_API_KEY
            )
            if not resolved_api_key or not resolved_api_key.strip():
                raise MissingAPIKeyError(
                    "OpenAI API key is missing. Set OPENAI_API_KEY in the environment or .env file."
                )
            self.client = ChatOpenAI(
                model=self.model,
                api_key=resolved_api_key,
                temperature=0.0,
            )

        if hasattr(self.client, "with_structured_output"):
            try:
                self.structured_client = self.client.with_structured_output(
                    GroundednessResult
                )
            except Exception:
                self.structured_client = None
        else:
            self.structured_client = None

        logger.info("Initialized GroundednessEvaluator with model: %s", self.model)

    def evaluate(
        self,
        query: str,
        draft_answer: str,
        retrieved_context: Sequence[str],
    ) -> GroundednessResult:
        """Determine whether the generated answer is supported by the retrieved context.

        Grounding rules:
        - A response is grounded only when its factual claims can be supported by retrieved context.
        - If unsupported claims exist: grounded = false
        - If context is insufficient or empty: grounded = false

        Args:
            query: Original user question.
            draft_answer: The draft answer to evaluate.
            retrieved_context: Retrieved document context chunks.

        Returns:
            GroundednessResult: Structured evaluation with grounded, grounding_score, unsupported_claims.

        Raises:
            ValueError: If query or draft_answer is invalid.
            GroundednessAPIError: If the evaluation API call fails.
        """
        if not isinstance(query, str) or not query.strip():
            raise ValueError("Query must be a non-empty string.")

        if not isinstance(draft_answer, str):
            raise ValueError(f"draft_answer must be a string, got {type(draft_answer).__name__}")

        clean_draft = draft_answer.strip()
        if not clean_draft:
            logger.info("Empty draft answer provided; marking ungrounded.")
            return GroundednessResult(
                grounded=False,
                grounding_score=0.0,
                unsupported_claims=["Draft answer is empty."],
            )

        has_context_content = any(
            bool(t.strip()) for t in retrieved_context if isinstance(t, str)
        )
        if not retrieved_context or not has_context_content:
            logger.info("Context is empty or insufficient; marking ungrounded.")
            return GroundednessResult(
                grounded=False,
                grounding_score=0.0,
                unsupported_claims=[
                    "Retrieved context is empty or insufficient to support the answer."
                ],
            )

        user_prompt = format_evaluator_prompt(
            query=query.strip(),
            draft_answer=clean_draft,
            retrieved_context=retrieved_context,
        )

        messages = [
            SystemMessage(content=GROUNDEDNESS_SYSTEM_PROMPT),
            HumanMessage(content=user_prompt),
        ]

        try:
            evaluator_runner = (
                self.structured_client
                if self.structured_client is not None
                else self.client
            )
            raw_response = evaluator_runner.invoke(messages)

            if isinstance(raw_response, GroundednessResult):
                parsed = raw_response
            elif isinstance(raw_response, dict):
                parsed = GroundednessResult(**raw_response)
            elif hasattr(raw_response, "content"):
                content = raw_response.content
                if isinstance(content, str):
                    parsed_dict = json.loads(content)
                    parsed = GroundednessResult(**parsed_dict)
                elif isinstance(content, dict):
                    parsed = GroundednessResult(**content)
                else:
                    raise ValueError(f"Unsupported content format: {type(content)}")
            else:
                raise ValueError(f"Unrecognized response format: {type(raw_response)}")

        except Exception as exc:
            logger.error("Groundedness evaluation API call failed: %s", exc)
            raise GroundednessAPIError(
                f"Groundedness evaluation failed: {exc}"
            ) from exc

        # Strict invariant enforcement:
        # If unsupported claims exist, grounded MUST be False
        unsupported = [
            str(claim).strip()
            for claim in parsed.unsupported_claims
            if str(claim).strip()
        ]
        is_grounded = bool(parsed.grounded and len(unsupported) == 0)

        raw_score = float(parsed.grounding_score)
        bounded_score = max(0.0, min(1.0, raw_score))

        if not is_grounded and bounded_score == 1.0:
            bounded_score = max(0.0, round(1.0 - (len(unsupported) * 0.3), 2))

        return GroundednessResult(
            grounded=is_grounded,
            grounding_score=bounded_score,
            unsupported_claims=unsupported,
        )


def check_groundedness(
    query: str,
    draft_answer: str,
    retrieved_context: Sequence[str],
    evaluator: GroundednessEvaluator | None = None,
) -> GroundednessResult:
    """Convenience function to evaluate groundedness of a draft answer against context."""
    service = evaluator or GroundednessEvaluator()
    return service.evaluate(
        query=query,
        draft_answer=draft_answer,
        retrieved_context=retrieved_context,
    )
